namespace Mws.Manifestador.Agent.Application.Commands;

public sealed record ListedCertificate(
    string Thumbprint,
    string Subject,
    string Issuer,
    string? CommonName,
    string? Document,
    string? DocumentType,
    string SerialNumber,
    string ValidFrom,
    string ValidTo,
    string NotBefore,
    string NotAfter,
    bool HasPrivateKey,
    string StoreLocation,
    string StoreName,
    string? Cnpj,
    bool IsExpired,
    bool IsCertificateAuthority,
    bool IsFiscalCandidate,
    bool IsIcpBrasil,
    bool IsUsableForClientAuth,
    string Classification,
    IReadOnlyCollection<string> RejectionReasons,
    IReadOnlyCollection<string> Warnings,
    bool IsValid,
    string? ValidationMessage);
